{% set version = "1.8.4" %}

package:
  name: pycomplexheatmap
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/P/PyComplexHeatmap/pycomplexheatmap-{{ version }}.tar.gz
  sha256: 6799d45e6ee44f0c74be0123645ce9dba779b8f39226d9f50409fde167fd0ec1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - wheel
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - numpy
    - pandas >=1.3.5
    - scipy
    - palettable

test:
  imports:
    - PyComplexHeatmap
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/DingWB/PyComplexHeatmap
  summary: A python package to plot complex heatmap
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mschilli87
